const BASE = '/api';

async function request(url, options = {}) {
  const res = await fetch(`${BASE}${url}`, {
    headers: { 'Content-Type': 'application/json' },
    ...options,
    body: options.body ? JSON.stringify(options.body) : undefined,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(err.message || err.error || 'API Error');
  }
  return res.json();
}

// Dùng riêng cho các endpoint trả về file binary (Excel, PDF)
// Dùng riêng cho các endpoint trả về file binary (Excel, PDF)
async function download(url, fallbackFilename) {
  try {
    const res = await request(url);
    if (res.url) {
      console.log('Final filename generated by Cloudinary:', res.url);
      window.open(res.url, '_blank');
    } else {
      throw new Error('No download URL returned from server');
    }
  } catch (error) {
    console.error('Error in download service:', error);
    alert('Không thể tải file, vui lòng kiểm tra lại cấu hình (VD: CLOUDINARY_URL)');
  }
}

export const api = {
  // Persons
  getPersons:       ()           => request('/persons'),
  getPerson:        (id)         => request(`/persons/${id}`),
  createPerson:     (data)       => request('/persons', { method: 'POST', body: data }),
  updatePerson:     (id, data)   => request(`/persons/${id}`, { method: 'PUT', body: data }),
  deletePerson:     (id)         => request(`/persons/${id}`, { method: 'DELETE' }),
  setCapabilities:  (id, caps)   => request(`/persons/${id}/capabilities`, { method: 'PUT', body: { capabilities: caps } }),
  setPermissions:   (id, perms)  => request(`/persons/${id}/permissions`,  { method: 'PUT', body: { permissions: perms } }),

  // Rooms
  getRooms:    ()         => request('/rooms'),
  createRoom:  (data)     => request('/rooms', { method: 'POST', body: data }),
  updateRoom:  (id, data) => request(`/rooms/${id}`, { method: 'PUT', body: data }),
  deleteRoom:  (id)       => request(`/rooms/${id}`, { method: 'DELETE' }),

  // Classes
  getClasses:          ()         => request('/classes'),
  createClass:         (data)     => request('/classes', { method: 'POST', body: data }),
  updateClass:         (id, data) => request(`/classes/${id}`, { method: 'PUT', body: data }),
  deleteClass:         (id)       => request(`/classes/${id}`, { method: 'DELETE' }),
  setClassPermissions: (id, perms)=> request(`/classes/${id}/permissions`, { method: 'PUT', body: { permissions: perms } }),

  // Time Slots
  getTimeSlots:    ()         => request('/time-slots'),
  createTimeSlot:  (data)     => request('/time-slots', { method: 'POST', body: data }),
  updateTimeSlot:  (id, data) => request(`/time-slots/${id}`, { method: 'PUT', body: data }),
  deleteTimeSlot:  (id)       => request(`/time-slots/${id}`, { method: 'DELETE' }),

  // Weeks
  getWeeks:         ()             => request('/weeks'),
  getWeek:          (id)           => request(`/weeks/${id}`),
  createWeek:       (data)         => request('/weeks', { method: 'POST', body: data }),
  updateWeekStatus: (id, status)   => request(`/weeks/${id}`, { method: 'PATCH', body: { status } }),

  // Availability
  getAvailability:  (weekId)                      => request(`/weeks/${weekId}/availability`),
  saveAvailability: (weekId, entries)              => request(`/weeks/${weekId}/availability`, { method: 'POST', body: { entries } }),
  copyAvailability: (weekId, previousWeekId)       => request(`/weeks/${weekId}/availability/copy`, { method: 'POST', body: { previous_week_id: previousWeekId } }),

  // Constraints
  getConstraints:    (weekId)        => request(`/weeks/${weekId}/constraints`),
  createConstraint:  (weekId, text)  => request(`/weeks/${weekId}/constraints`, { method: 'POST', body: { raw_text: text } }),
  updateConstraint:  (weekId, cid, data) => request(`/weeks/${weekId}/constraints/${cid}`, { method: 'PUT', body: data }),
  deleteConstraint:  (weekId, cid)   => request(`/weeks/${weekId}/constraints/${cid}`, { method: 'DELETE' }),

  // Sessions (Pins)
  getSessions:   (weekId)       => request(`/weeks/${weekId}/sessions`),
  pinSession:    (weekId, data) => request(`/weeks/${weekId}/pin`, { method: 'POST', body: data }),
  deleteSession: (weekId, sid)  => request(`/weeks/${weekId}/sessions/${sid}`, { method: 'DELETE' }),
  updateSessionAssignment: (sid, personId, role, taId, taRole) => request(`/sessions/${sid}/assignment`, { method: 'PUT', body: { person_id: personId, role, ta_id: taId, ta_role: taRole } }),

  // Export
  exportExcel: (weekId) => download(`/weeks/${weekId}/export/excel`, `TKB_${weekId}.xlsx`),
  exportPdf:   (weekId) => download(`/weeks/${weekId}/export/pdf`,   `TKB_${weekId}.pdf`),
  exportCustom: (weekId, format, views) => request(`/weeks/${weekId}/export`, { method: 'POST', body: { format, views } }),
};
